name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make linux bin # not actual make
        run: make build-gpp

      - name: upload linux artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: formula
          path: ./formula

  win-build:
    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v2  
     - uses: ilammy/msvc-dev-cmd@v1  
     - name: cl build
       run: cl /EHsc index.cc
       
     - name: upload win artifact
       uses: actions/upload-artifact@v2.2.1
       with:
        name: formula
        path: .\index.exe
