name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install mingw-w64
      run: sudo apt-get install mingw-w64
    - name: make linux bin # not actual make
      run: g++ -o formula index.cc
    - name: make win
      run: make win
      
    - name: upload linux artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: formula 
        path: ./formula
        
    - name: upload win artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: formula-win
        path: ./lol.exe
