name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install mingw-w64
        run: sudo apt-get install mingw-w64
      - name: make linux bin # not actual make
        run: make build-gpp

      - name: upload linux artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: formula
          path: ./formula

  win-build:
    runs-on: windows-latest

    steps:
      - name: Bazel Action
        uses: ngalaiko/bazel-action@2.0.0
        with:
          args: # default is
          - uses: actions/checkout@v2
          
      - name: bazel build formula
      run: bazel build //:formula
